### ISSUE TITLE
_alreayCompletedSteps where was called on null

### ISSUE THREAD

**Issue by awhitford** [ayalma/feature_discovery#35]
Just tried **upgrading from 0.10.0 to 0.12.0** and receiving this exception:
```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'where' was called on null.
Receiver: null                                                          
Tried calling: where(Closure: (String) => bool)                         
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)    
#1      Bloc._alreayCompletedSteps (package:feature_discovery/src/foundation/bloc.dart:159:10)
<asynchronous suspension>                                               
#2      Bloc.discoverFeatures (package:feature_discovery/src/foundation/bloc.dart:111:28)
#3      FeatureDiscovery.discoverFeatures (package:feature_discovery/src/foundation/feature_discovery.dart:32:24)
#4      _HomeScreenState.initState.<anonymous closure> (package:kozzeted/screens/home_screen.dart:65:24)
#5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
#6      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1060:9)
#7      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
#8      _rootRun (dart:async/zone.dart:1184:13)                         
#9     <…>  
```

It appears that `_alreayCompletedSteps` is trying to reference `_steps` before it has been initialized.

Oh, and I presume `_alreayCompletedSteps` should be `_alreadyCompletedSteps` .

**Comment by awhitford** [comment]
Will you be releasing a patch?

**Comment by axel-op** [comment]
@ayalma

**Comment by ayalma** [comment]
Released 
Thank you

**Comment by narcodico** [comment]
Hey @ayalma, this doesn't seem fixed. I'm getting the exact same error with `0.12.1`.

```
I/flutter (17796): NoSuchMethodError: The method 'where' was called on null.
I/flutter (17796): Receiver: null
I/flutter (17796): Tried calling: where(Closure: (String) => bool)
I/flutter (17796):
I/flutter (17796): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
I/flutter (17796): #1      Bloc._alreadyCompletedSteps
package:feature_discovery/…/foundation/bloc.dart:160
I/flutter (17796): <asynchronous suspension>
I/flutter (17796): #2      Bloc.discoverFeatures
package:feature_discovery/…/foundation/bloc.dart:112
I/flutter (17796): #3      FeatureDiscovery.discoverFeatures
package:feature_discovery/…/foundation/feature_discovery.dart:32
I/flutter (17796): #4      _HomeState.initState.<anonymous closure>.<anonymous closure>
package:dotasuperstar/…/view/home_view.dart:55
I/flutter (17796): #5      _rootRun (dart:async/zone.dart:1182:47)
I/flutter (17796): #6      _CustomZone.run (dart:async/zone.dart:1093:19)
I/flutter (17796): #7      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
I/flutter (17796): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
I/flutter (17796): #9      _rootRun (dart:async/zone.dart:1190:13)
I/flutter (17796): #10     _CustomZone.run (dart:async/zone.dart:1093:19)
I/flutter (17796): #11     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
I/flutter (17796): #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037

```

**Comment by narcodico** [comment]
Your method
```
void discoverFeatures(Iterable<String> steps) async
```
should actually return a `Future<void>`.
Due to asynchronous matter of the code setting a local variable and working with it is problematic.
You'd be better of doing something like:
```
_stepsToIgnore = await _alreadyCompletedSteps(steps);
    _stepsController.add(_steps.where((s) => !_stepsToIgnore.contains(s)).toList());
```
Keeping local state in a bloc is not recommended, since everything should be handled through `Sinks` and `Streams`.
You could handle your steps with the help of a `StreamController`.

**Comment by henry2man** [comment]
@ayalma @narcodico Is there any workarround for this issue? I'm having it but I'm not pretty sure how can I deal with it.
